#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Turn the wolf's GIFs into avatar/wolf/wolf_sprites.c for avatar/wolf/muse_pixel_wolf.c.

Each source is a 320 x 320 GIF of five frames: standing, eyes shut, standing,
a pose (a hop for the body, a head tilt for the head), standing. This keeps
frames 0, 1 and 3 of each, takes out the dark background (whatever dark
reaches in from the edge, so the nose and the eyes' pupils stay), and scales
them to the avatar's 64 x 64 grid: the body standing on the grid's floor, the
head (the logo shown while booting) centred. One palette covers every frame;
index 0 is the transparent background.

Usage: gen_wolf_avatar.py [BODY.gif HEAD.gif]   (requires Pillow)
"""

import pathlib
import sys

from PIL import Image, ImageSequence

ROOT = pathlib.Path(__file__).resolve().parent.parent
WOLF = ROOT / "avatar" / "wolf"
OUT = WOLF / "wolf_sprites.c"

GRID = 64
FRAMES = (0, 1, 3)          # standing, eyes shut, pose
COLOURS = 47                # plus the background
BODY_HEIGHT = 50            # grid rows the standing body fills
BODY_FLOOR = 59             # the row its feet stand on
HEAD_SIZE = 48


def frames(path):
    gif = Image.open(path)
    out = [f.convert("RGB") for f in ImageSequence.Iterator(gif)]
    return [out[i] for i in FRAMES]


def background_mask(img, dark):
    """Pixels darker than `dark` that join the image's edge."""
    w, h = img.size
    px = img.load()
    bg = bytearray(w * h)
    stack = [(x, y) for x in range(w) for y in (0, h - 1)] + [(x, y) for y in range(h) for x in (0, w - 1)]
    while stack:
        x, y = stack.pop()
        i = y * w + x
        if bg[i] or max(px[x, y]) > dark:
            continue
        bg[i] = 1
        for nx, ny in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
            if 0 <= nx < w and 0 <= ny < h:
                stack.append((nx, ny))
    mask = Image.new("L", (w, h))
    mask.putdata([0 if b else 255 for b in bg])
    return mask


def bbox(masks):
    boxes = [m.getbbox() for m in masks]
    return (min(b[0] for b in boxes), min(b[1] for b in boxes), max(b[2] for b in boxes), max(b[3] for b in boxes))


def to_grid(imgs, dark, place):
    """Cuts out, crops all frames alike and scales them; returns RGBA grids."""
    masks = [background_mask(i, dark) for i in imgs]
    box = bbox(masks)
    out = []
    for img, mask in zip(imgs, masks):
        rgba = img.copy()
        rgba.putalpha(mask)
        rgba = rgba.crop(box)
        w, h, x, y = place(rgba.size)
        # Colour from opaque pixels only, so the edges don't pick up the background.
        small = rgba.resize((w, h), Image.BOX)
        grid = Image.new("RGBA", (GRID, GRID), (0, 0, 0, 0))
        grid.paste(small, (x, y))
        out.append(grid)
    return out


def place_body(size):
    w, h = size
    s = BODY_HEIGHT / h
    gw, gh = round(w * s), BODY_HEIGHT
    return gw, gh, (GRID - gw) // 2, BODY_FLOOR - gh


def place_head(size):
    w, h = size
    s = HEAD_SIZE / max(w, h)
    gw, gh = round(w * s), round(h * s)
    return gw, gh, (GRID - gw) // 2, (GRID - gh) // 2


def main():
    body_gif = sys.argv[1] if len(sys.argv) > 2 else WOLF / "source" / "wolf_body.gif"
    head_gif = sys.argv[2] if len(sys.argv) > 2 else WOLF / "source" / "wolf_head.gif"
    grids = to_grid(frames(body_gif), 24, place_body) + to_grid(frames(head_gif), 40, place_head)

    # One palette for all six frames: quantize them side by side.
    strip = Image.new("RGB", (GRID * len(grids), GRID))
    for i, g in enumerate(grids):
        strip.paste(g.convert("RGB"), (i * GRID, 0))
    pal_img = strip.quantize(colors=COLOURS, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE)
    pal = pal_img.getpalette()[: COLOURS * 3]
    colours = [tuple(pal[i * 3 : i * 3 + 3]) for i in range(COLOURS)]

    data = []
    for i, g in enumerate(grids):
        q = pal_img.crop((i * GRID, 0, (i + 1) * GRID, GRID)).load()
        a = g.getchannel("A").load()
        data.append([0 if a[x, y] < 128 else q[x, y] + 1 for y in range(GRID) for x in range(GRID)])

    lines = [
        "// Generated by tools/gen_wolf_avatar.py from avatar/wolf/source/. Do not edit.",
        "",
        '#include "wolf_sprites.h"',
        "",
        f"const uint32_t wolf_palette[WOLF_COLOURS] = {{",
        "    0x000000,   /* background */",
    ]
    lines += [f"    0x{r:02x}{g:02x}{b:02x}," for r, g, b in colours]
    lines += ["};", ""]
    names = ("WOLF_BODY", "WOLF_BODY_BLINK", "WOLF_BODY_HOP", "WOLF_HEAD", "WOLF_HEAD_BLINK", "WOLF_HEAD_TILT")
    lines.append("const uint8_t wolf_frames[WOLF_FRAMES][WOLF_GRID * WOLF_GRID] = {")
    for name, d in zip(names, data):
        lines.append(f"    [{name}] = {{")
        for y in range(GRID):
            row = d[y * GRID : (y + 1) * GRID]
            lines.append("        " + ",".join(f"{v}" for v in row) + ",")
        lines.append("    },")
    lines += ["};", ""]
    OUT.write_text("\n".join(lines))

    hdr = [
        "// Generated by tools/gen_wolf_avatar.py from avatar/wolf/source/. Do not edit.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define WOLF_GRID {GRID}",
        f"#define WOLF_COLOURS {COLOURS + 1}   /* index 0 is the background */",
        f"#define WOLF_FLOOR {BODY_FLOOR}",
        "",
        "enum { " + ", ".join(names) + ", WOLF_FRAMES };",
        "",
        "extern const uint32_t wolf_palette[WOLF_COLOURS];",
        "extern const uint8_t wolf_frames[WOLF_FRAMES][WOLF_GRID * WOLF_GRID];",
        "",
    ]
    (WOLF / "wolf_sprites.h").write_text("\n".join(hdr))
    print(f"{OUT.relative_to(ROOT)}: {len(grids)} frames, {COLOURS + 1} colours")


if __name__ == "__main__":
    main()
