// Generated by tools/gen_wolf_avatar.py from avatar/wolf/source/. Do not edit.
#pragma once

#include <stdint.h>

#define WOLF_GRID 64
#define WOLF_COLOURS 48   /* index 0 is the background */
#define WOLF_FLOOR 59

enum { WOLF_BODY, WOLF_BODY_BLINK, WOLF_BODY_HOP, WOLF_HEAD, WOLF_HEAD_BLINK, WOLF_HEAD_TILT, WOLF_FRAMES };

extern const uint32_t wolf_palette[WOLF_COLOURS];
extern const uint8_t wolf_frames[WOLF_FRAMES][WOLF_GRID * WOLF_GRID];
